### ISSUE TITLE
REST service to update an existing Rasa rule

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#114]
AS AN Architect
I WANT to have a REST service to update an existing Rasa rule
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

- [ ] Use POST service `/rasa/rules/update`
- [ ] Apply changes on [Rasa rules.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/rules.yml)
- [ ] Changes apply only in case #113 responds with `HTTP 200`
- [ ] When updating a rule, use #111 to re-write an existing slot with new content

**Comment by RaulAltmae** [comment]
sample input for `/rasa/rules/update`
```json
{
  "rule": "tervitused",
  "steps": [
    {
      "intent": "greeing_ee"
    },
    {
      "intent": "greeing_en"
    },
    {
      "action": "utter_laters"
    }
  ]
}
```

**Comment by turnerrainer** [comment]
@RaulAltmae please link this issue with an appropriate pull request.

**Comment by RaulAltmae** [comment]
Pull request https://github.com/buerokratt/Training-Module/pull/157

**Comment by ValterAro** [comment]
Short summary: Can not edit any of the rules in the list. When clicking on the edit button, it takes to an empty page.
Real result: user is taken to an empty page
Expected result: User can edit the selected rule
How to reproduce: After logging in, go to https://admin.dev.buerokratt.ee/training/training/stories and select rules. Then try to edit any of the rules.
Pic:


![Image](https://github.com/buerokratt/Training-Module/assets/122787093/01150a88-a27e-4e57-9302-7cd95210b72a)
