### ISSUE TITLE
Common intents training module (GUI)

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#29]
### **Acceptance Criterias:**
- [ ] Common topics will be distinguished from local intents #10 
- [ ] View and edit rules/stories/responses for common intents (original model must be commented out, but kept in the dataset);

**GUI Story's:**
- [ ] tba
- [ ] tba

**DSL Story's:**
- [ ] tba
- [ ] tba

**Comment by turnerrainer** [comment]
@vmugra 
The difference here compared to other intents training module GUI functionalities are only limited to different data sets, right?

**Comment by vmugra** [comment]
@turnerrainer o

**Comment by turnerrainer** [comment]
@vmugra 
Makes sense. Just a separate DSL then, no GUI developments needed.

**Comment by ceirowe** [comment]
@turnerrainer 
We discussed earlier, that common intents and organization intents will be separated into different views. This means GUI developments are still needed here.

**Comment by vmugra** [comment]
Solved with task #10
