### ISSUE TITLE
Database refactoring for Training Module

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#350]
AS AN Architect
I WANT Training Module Postgres databases and their tables to be refactored
SO THAT they would be compliant with best practices

### Acceptance Criteria

- [ ] All AC from https://github.com/buerokratt/Buerokratt-Architectural-Decision-Records/issues/46 apply

**Comment by KasparMinn** [comment]
Currently, it seems that the database in the Training Module does not need any refactoring. 

The training module database (postgres) only has one table and it is for intents. As it stands today, only a single operation fetches data from the intents table - getting the 'last modified' date information on opening any specific intent in the Training Module. The columns seem to be compliant with best practices: ID (bigint), intent (varchar), created (timestamp with time zone) and status (varchar(10)).

On any sort of CRUD operation with intents, the only statement that is used is INSERT. 
- On adding a new intent, it inserts a new line with the intent's name and an ACTIVE status. 
- On deleting an intent, it inserts a new line with the intent's name and a DELETED status.
- On updating an intent, it inserts a new line with the intent's updated name and an ACTIVE status, and changes the old to DELETED.

This is useful for tracking all changes made for intents.
On fetching the 'last changed' data, it just fetches the timestamp of the recently created line with the input intent name and the front-end converts it into a readable format.

**Comment by 1AhmedYasser** [comment]
> Currently, it seems that the database in the Training Module does not need any refactoring.
> 
> As it stands today, the training module database (postgres) only has one table and it is for intents. Only a single operation fetches data from the intents table - getting the 'last modified' date information on opening any specific intent in the Training Module. The columns seem to be compliant with best practices: ID (bigint), intent (varchar), created (timestamp with time zone) and status (varchar(10)).
> 
> On any sort of CRUD operation with intents, the only statement that is used is INSERT.
> 
> * On adding a new intent, it inserts a new line with the intent's name and an ACTIVE status.
> * On deleting an intent, it inserts a new line with the intent's name and a DELETED status.
> * On updating an intent, it inserts a new line with the intent's updated name and an ACTIVE status, and changes the old one to DELETED.
> 
> This is useful for tracking all changes made for intents.
> 
> On fetching the 'last changed' data, it just selects the timestamp of the recently created line with the input intent name and the front-end converts it into a readable format.

@turnerrainer Most of training module operations are done via Open Search and it does not use the chatbot db and it has only 1 table `intents` with the correct data types, so no liquibase queries are required here

**Comment by turnerrainer** [comment]
Close due to @KasparMinn and @1AhmedYasser valid comments.
