### ISSUE TITLE
Connect an intent to a Service

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Training-Module#362]
AS an Administrative User
I WANT TO link an intent to the Service
SO THAT the intent would trigger the service flow, not the single response

Duplicate of https://github.com/buerokratt/Service-Module/issues/30 with changes to the process flow and several other updates.

### Acceptance criteria

**Button**
- [x] An additional button "Seo teenusega" / "Connect to a Service" is added above examples of a selected intent in addition to the ones shown below
![image](https://user-images.githubusercontent.com/90505798/220581338-61cfb603-5ff8-4a2f-8295-2bd6f50e4a3b.png)
- [x] the button must have a Tooltip with the text "to connect the service, the service must be previously created in the Services module"

**Intents**
- [ ] Any intent can be turned into a Service
- [ ] Rasa-specific validations when turning an existing story into a Service - _Use [1.2 Change existing intent to service from RASA_service_module.docx](https://github.com/buerokratt/Service-Module/files/10988896/RASA_service_module.docx) by @KlviG as a reference_
- [ ] Only 1 intent can be linked to a specific Service
- [ ] Intents have different background colors based on being a Service or a Rasa response
- [ ] Intent response can be used as fallback message, when Service is in INACTIVE or DRAFT state (see https://github.com/buerokratt/Service-Module/issues/195)

**Drop-down menu**
- [ ] When pressing the "Connect to a Service" button: 
1. intent is changed to Service-intent, available for [Integration Layer](https://github.com/buerokratt/Training-Module/issues/397)
2. user role enquiry is performed
3. when user has Service Manager role (access to Service Module), a drop-down menu appears in the training module with available services (those **not yet associated** with the intent)
4. when user has no Service Manager role, message is displayed "only Service Managers can connect Services"
- [ ] The length of the drop-down menu is max 8 services, and if more, it can be scrolled
- [ ] When no services available, message is displayed "No services are ready to be connected"
- [ ] Services in drop-down menu are displayed in alphabetical order
- [ ] After making a selection, a confirmation modal will appear, whether you are sure you want to connect to this service -> YES/NO. Example: https://www.figma.com/file/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?type=design&node-id=2472-18906&mode=design&t=0pW2q0viwq0BB4Zy-4
- [ ] Success message for successful pairing or error if unsuccessful

**Changing and deleting**
- [ ] It must be possible to change the associated service later (e.g. if something went wrong by accident and you wanted to associate another service). "Connect to a Service" button -> new name after first connection is done: "Change service" -> triggering drop-down menu.
- [ ] Necessary explanation as a Tooltip when hovering over the Delete button - "Only the Intent is deleted and the service remains, its deletion can be done in the Service module". 
- [ ] The tooltip on Delete button appears only when intent is connected to the Service.

**Comment by rasmusei** [comment]
Need DSL grooming

**Comment by bartekpospiech** [comment]
https://github.com/buerokratt/Training-Module/pull/382

**Comment by Kristjan259** [comment]
Gives network error when I press "change into service" button. Seems it is still connected to localhost.

![Image](https://github.com/buerokratt/Training-Module/assets/5470201/d5370a55-7c4b-4c7d-8f1e-b7cbcca08c21)

**Comment by Kristjan259** [comment]
Seems that the change into service button is connected to a localhost url

![Image](https://github.com/buerokratt/Training-Module/assets/5470201/3ef7e98a-b014-48fa-907d-c8b2cc2075cc)

**Comment by Kristjan259** [comment]
When pressing connect to a service button, then it is unable to fetch services.



![Image](https://github.com/buerokratt/Training-Module/assets/5470201/c5138357-0158-46dc-a8fd-7b80c395f371)

**Comment by 1AhmedYasser** [comment]
> When pressing connect to a service button, then it is unable to fetch services.
> 
> ![Image](https://private-user-images.githubusercontent.com/5470201/314429460-c5138357-0158-46dc-a8fd-7b80c395f371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDcwMDAsIm5iZiI6MTcxMDk0NjcwMCwicGF0aCI6Ii81NDcwMjAxLzMxNDQyOTQ2MC1jNTEzODM1Ny0wMTU4LTQ2ZGMtYThmZC03YjgwYzM5NWYzNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMTQ1ODIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjAxOTczYzEwZmIyYWNiZWQwZDJkYjQyY2U3ZmFjMzI0Y2U2NWNmZGI2OTZlMWYwYjVlMGIyZTJjZjI2NDU0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XM3uw4VGEjLJNbUFKqzJ-L-bUHdKWobcnWGrU9UQaXo)

@baha-a do we need any changes on dev or local to make it work ?

**Comment by baha-a** [comment]
> Seems that the change into service button is connected to a localhost url
> 
> ![Image](https://private-user-images.githubusercontent.com/5470201/314428453-3ef7e98a-b014-48fa-907d-c8b2cc2075cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NzY2MjUsIm5iZiI6MTcxMDk3NjMyNSwicGF0aCI6Ii81NDcwMjAxLzMxNDQyODQ1My0zZWY3ZTk4YS1iMDE0LTQ4ZmEtOTA3ZC1jOGIyY2MyMDc1Y2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMjMxMjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDdiZDgwODE1MzI2YmNmZDcwYTBlZTQ0OWFiY2Y5ZmI2OWZlYTA2OWRhYjllYTFkM2FjZWI0YzMwODMyYzQ2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UmDdVhIHD6RnGyeatUYNF0az_2yGgK8bQSodfacr7B4)

- Localhost request appears after clicking on `Mudda teenuseks` button which was implemented long ago and not part of this task.

- The `Seo teenusega` button was added as part of this task. However, after you click it, browser fetch data from:
  
  _`https://ruuter.dev.buerokratt.ee/priv2/services/get-services-not-assigned-to-intent`_
  
  but it seams the correct URL should have been:
  
  _`https://ruuter.dev.buerokratt.ee/training/services/get-services-not-assigned-to-intent`_
  
  as the first one returns `300 Multiple Choices` with no response, and the second one return JSON response but with "Internal Server Error".

**Comment by 1AhmedYasser** [comment]
> @1AhmedYasser,
> 
> 
> 
> - Localhost request appears after clicking on `Mudda teenuseks` button which was implemented long ago and not part of this task.
> 
> 
> 
> - The `Seo teenusega` button was added as part of this task. However, after you click it, browser fetches data from:
> 
>   
> 
>   _https://ruuter.dev.buerokratt.ee/priv2/services/get-services-not-assigned-to-intent_
> 
>   
> 
>   but it seams the correct URL should have been:
> 
>   
> 
>   _https://ruuter.dev.buerokratt.ee/training/services/get-services-not-assigned-to-intent_
> 
>   
> 
>   as the first one returns `300 Multiple Choices` with no response, and the second one return JSON response but with "Internal Server Error".
> 
> 
> 
> - Also similarly, navigating to https://admin.dev.buerokratt.ee/training/auto-services doesn't work, but https://admin.dev.buerokratt.ee/training/training/auto-services works fine. This page fetches data from:
> 
>   
> 
>   _https://ruuter.dev.buerokratt.ee/priv2/services/connection-requests_
> 
> 
> 
>   which returns `300 Multiple Choices`, however, it will work just fine if you change it to:
> 
>   
> 
>   _https://ruuter.dev.buerokratt.ee/training/services/connection-requests_
> 
> 

@baha-a i think we need a meeting with @KlviG or @varmoh regarding this

**Comment by baha-a** [comment]
@KlviG, [This PR #411](https://github.com/buerokratt/Training-Module/pull/411) should resolve `300 Multiple Choices` problems.

**Comment by turnerrainer** [comment]
@ValterAro please test again as according to @1AhmedYasser, some external developments might have fixed this issue.

**Comment by ValterAro** [comment]
Short summary: Can't turn an intent into a service. You get an error message saying "Network error".
How to reproduce: login and go to https://admin.dev.buerokratt.ee/training/training/intents , then create an intent and try to turn it into a Service.
Pic:


![Image](https://github.com/buerokratt/Training-Module/assets/122787093/c1052a2a-b42c-4b15-b0a3-4d7f7511afed)

**Comment by ValterAro** [comment]
Short summary: When trying to connect an intent with error, then there is a failure to get the list of services.
How to reproduce: Login and go to https://admin.dev.buerokratt.ee/training/training/intents , then create a new intent and try to connect it with a service.
Pic:


![Image](https://github.com/buerokratt/Training-Module/assets/122787093/512bd7f3-a011-4c1a-b373-56da19d96533)

**Comment by ValterAro** [comment]
This can not be tested before the list of intents is fixed in the training module. https://admin.dev.buerokratt.ee/training/training/intents

Pic of current situation:


![Image](https://github.com/buerokratt/Training-Module/assets/122787093/03e5c266-9245-4f7f-806f-dc07acf2d78e)

**Comment by rasmusei** [comment]
Solved in another task
