### ISSUE TITLE
Synchronize training settings data in database and YAML files

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#392]
AS AN Architect
I WANT training settings data in database and YAML files to be synchronized
SO THAT the data stored in database could also be used as input for functionalities that only access data from YAML files

### Acceptance Criteria

- [ ] Use database table `train_settings` as source
- [ ] Only synchronize data from database to YAML, not vice versa
- [ ] Trigger synchronization as part of an appropriate #385 Ruuter DSL step

#### Scope

> Initial scope of work is to make changes on local files

- [ ] `Docker Compose` [that triggers Rasa training](https://github.com/buerokratt/Installation-Guides/blob/main/default-setup/chatbot-and-training/bot_training/docker-compose.yml)
- [ ] [CronManager](https://github.com/buerokratt/CronManager)

**Comment by ExiRain** [comment]
[Pull request](https://github.com/buerokratt/Training-Module/pull/395) with changes.

**Comment by turnerrainer** [comment]
Works as intended
