### ISSUE TITLE
GUI to confirm/reject propositions to link intents with specific Services

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#400]
AS A Chatbot Trainer and/or Service Manager
I WANT TO confirm/reject propositions to link intents with specific Services
SO THAT Services could be proposed to be initiated when a specific intent has been detected and vice versa

### Acceptance Criteria

- [ ] GUI is called "Auto-Services"
- [ ] List of intents is shown
- [ ] List of Services is shown
- [ ] Intents can be proposed to be linked with a specific Service
- [ ] Services can be proposed to be linked with a specific intent
- [ ] Propositions to link an intent with a specific Service can be rejected
- [ ] Propositions to link a Service with a specific intent can be rejected
- [ ] Already linked intent can be unlinked
- [ ] Already linked Service can be unlinked

#### Main Menu

- [ ] Replace the path under /services/followupTraining in service module with the attached path
- [ ] Add a new path under /training/autoServices in training module with the attached path

> Path

```
{
  "label": {
     "et": "Iseteenused",
     "en": "Auto Services"
  },
  "path": “/Auto-Services
}
```

**Comment by 1AhmedYasser** [comment]
@bartekpospiech @turnerrainer @ExiRain 

the path added to menu is the following

```
{
    "label": {
        "et": "Automatic Teenused",
        "en": "Automatic Services"
     },
     "path": "/auto-services"
}
```
