### ISSUE TITLE
Docker Compose to set up back-end of Training Module on a local environment

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#41]
AS AN DevOps
I WANT TO set up Bürokratt's Training Module's back-end functionality as a Docker image
SO THAT I could test its functionalities locally or run it as a service on my preferred infrastructure

### Acceptance Criteria

After running `docker-compose up -d` on Terminal, the following AC are fulfilled

- [ ] Ruuter is set up, [existing Dockerfile as a reference](https://github.com/buerokratt/Ruuter/blob/main/Dockerfile)
- [ ] Resql is set up, [existing Dockerfile as a reference](https://github.com/buerokratt/Resql/blob/main/Dockerfile)
- [ ] OpenSearch is set up
- [ ] Nodejs is set up

**Comment by turnerrainer** [comment]
@RaulAltmae please provide Docker Compose

**Comment by varmoh** [comment]
Pull request https://github.com/buerokratt/Training-Module/pull/201
