### ISSUE TITLE
Refactor all Training Module's Postgres queries to replace `DELETE` queries with `INSERT` and `SELECT`

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#488]
> [!IMPORTANT]
> This is a sub-issue of https://github.com/buerokratt/Buerokratt-Chatbot/issues/483

### Acceptance Criteria

- [ ] All AC of [an epic](https://github.com/buerokratt/Buerokratt-Chatbot/issues/483) apply

#### Scope

- [ ] https://github.com/buerokratt/Training-Module/tree/dev/DSL/Resql

**Comment by baha-a** [comment]
The `DELETE` command is not used in the Training Module, so this task should be closed.

**Comment by turnerrainer** [comment]
> The `DELETE` command is not used in the Training Module, so this task should be closed.
