### ISSUE TITLE
Search within previous conversations

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#5]
AS A Service Manager
I WANT TO search conversations based on given criterias
SO THAT I could easily find appropriate conversations

### Acceptance Criteria

- [ ] Full-text search
- [ ] Within all available criteria
- [ ] Filter results

#### DSL

- [ ] #37
- [ ] #38

**Endpoints**

_Views: [Ajaloolised vestlused vaade - UXUI tba](https://www.figma.com/proto/rILEM6rghNvTsEKJ1wyQBn/B%C3%BCrokratt?node-id=27%3A1150&starting-point-node-id=1%3A2)
Loogika sarnane -> vasakult vali "vestlus" sektsioon ajalooliste vestlustega_

- [ ] tba
- [ ] tba

**Comment by turnerrainer** [comment]
Priority 1 to kick-start the technical solution + GUI + UX plans.

**Comment by RaulAltmae** [comment]
> Within all available criterias

What are all available criterias?
