### ISSUE TITLE
Make the list of intents and examples separately scrollable in Training Module

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Training-Module#639]
AS A Backoffice User
I WANT TO scroll through the list of intents and intent examples separately in /training/training/intents
SO THAT when scrolling through the list of intents, the options for a selected intent will not scroll

Currently the list of intent names scrolls together with selected intent examples as shown in the video:
https://github.com/user-attachments/assets/d966df2b-2758-4e2a-a96a-aa1c47721785

**Comment by rasmusei** [comment]
https://github.com/buerokratt/Training-Module/pull/637

**Comment by ffrose** [comment]
As well as intent list and example list, it is still possible to scroll down the whole page.
![image](https://github.com/user-attachments/assets/813f6a63-76bb-4c7b-ab67-7e0289c6d421)

**Comment by ffrose** [comment]
Still possible to scroll the whole page in /training/training/intents. Should be able to scroll only intents and examples.

**Comment by jaX10bt** [comment]
Works as intended
