### ISSUE TITLE
[BUG] Search function not working in Training Module history

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Training-Module#642]
AS A Backoffice User
I WANT TO be able to search historical chats in Training Module like in Chat Module
SO THAT I have the same functionalities as in Chat Module

Currently the search text input box in /training/history/history is not doing anything

**Comment by rasmusei** [comment]
@yb-ng, this is related to task https://github.com/buerokratt/Buerokratt-Chatbot/issues/122 and https://github.com/buerokratt/Buerokratt-Chatbot/issues/19

**Comment by jaX10bt** [comment]
Search function still not working in Training Module

https://github.com/user-attachments/assets/239398c2-cd7d-4e31-bce0-1b76dff9d19f

**Comment by ffrose** [comment]
[BUG]
in /chat/history i am able to search using only the Chat ID value

In /training/training/history i am able to search with Chat ID value and Chat content.

I should be able to search in both views, with the following options:
Chat ID
CSA's name
by date
End Users name
Personal ID code
content of the chat

**Comment by jaX10bt** [comment]
Works as intended. Refined scope for case insensitive search in a new task.
