### ISSUE TITLE
[BUG] Changing Intent name under training is not working

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Training-Module#677]
**Bug description:** When I try to change to Intent (Teema) name under Intents (Teemad) in Training module, I'll get an error message that something went wrong.

**Expected behavior:** Changing intents name should be working. When I change intents name it should be saved properly and shown in the GUI

**Screenshots:** ![Image](https://github.com/user-attachments/assets/b531d10d-fb7c-4d0d-be8b-754b3f25c5cd)

**Additional information:**

**Comment by IgorKrupenja** [comment]
Related PR: https://github.com/buerokratt/Training-Module/pull/681

**Comment by jaX10bt** [comment]
Works as intended
