### ISSUE TITLE
[BUG] Downloading intent examples

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Training-Module#678]
**Bug description:** When downloading intent examples it is not possible where to save the file. It will just download the file. Probably will use browser settings for the location

**Expected behavior:** When downloading intent examples, I should be able to select the location where I want to save the file.

**Screenshots:**

**Additional information:**

**Comment by IgorKrupenja** [comment]
Useful:

- https://stackoverflow.com/questions/67804382/force-showing-the-save-as-dialog-box-when-downloading-a-file
- https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker#browser_compatibility
- https://web.dev/patterns/files/save-a-file

**Comment by IgorKrupenja** [comment]
Related PR: https://github.com/buerokratt/Training-Module/pull/706

As discussed with @RiinaLi, it is [only possible to implement in Chromium-based browsers](https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker#browser_compatibility).

Please test:

- Chrome: save dialog now appears in Chrome when clicking on the button to download intent examples.
- Safari & Firefox: no change, file download starts immediately without showing a save dialog.
- Test this on both Intents and Common intents pages.

**Comment by ffrose** [comment]
Works as intended. Can download both Intents and Common Intents.
