### ISSUE TITLE
[BUG] Links in training historical chats not clickable

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Training-Module#698]
**Bug description:**
Links in Training Module historical chats (/training/history/history) are not clickable

**Expected behavior:**
Links in Training Module historical chats should be clickable just like in Chat Module historical chats.

**Screenshots:**
![Image](https://github.com/user-attachments/assets/5f1846af-8947-4666-84d0-eae4a3002c26)

**Comment by 1AhmedYasser** [comment]
@ExiRain links should direct user to a new tab, please add a new small change

here

```
<Markdown options={{ enforceAtxHeadings: true, overrides: { a: { props: { target: "_blank" } } } }}>
      {message ?? ""}
    </Markdown>
```

**Comment by jaX10bt** [comment]
Works as intended
