### ISSUE TITLE
GUI for historical conversations

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#70]
### Acceptance criterias:

- [x] Display list of all historical conversations
- [x] View button for displaying specific conversation

**Add new examples based on client messages**
- [x] For each client message add new example for intents (add new intent if needed)
- [x] Add new intent name!
- [x] –If add new intent is chosen - display a textbox for intent name (choose if common or not) and add  or cancel– 
- [x] Save intent to an example in "Teemad" -> "Intent"

**Add new responses or replace ones based on client messages**
- [x] For each customer support agent message add new response
- [x] Choose from list of responses (below display current utter_chosen_response message)
- [x] Add new response! "utter_new"
- [x] Display current message of selected response
- [x] Ask confirmation to modify
- [x] Add response/or cancel

**Flag messages**

- [ ] Flag conversation and highlight it in the conversation list

**Comment by ceirowe** [comment]
@vmugra Prototype updated according to AC-s.

**Comment by vmugra** [comment]
@ceirowe There is something off with the pop-up:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/46499312/220281800-9f4406ac-502a-456a-9667-9764a23e4236.png">

**Comment by AlarWE** [comment]
@vmugra  Prototype updated

**Comment by vmugra** [comment]
@AlarWE this needs fixing!

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/46499312/225850675-19bff244-8ea9-4cc1-85c4-ca2b676cb4f4.png">

**Comment by vmugra** [comment]
<img width="810" alt="image" src="https://user-images.githubusercontent.com/46499312/225850953-c1289b13-ecd0-417c-86fd-ed91f2aa2d09.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/46499312/225851014-4fe670b9-b126-4634-9c76-0d38f79ac227.png">

**Comment by vmugra** [comment]
> @AlarWE this needs fixing!
> 
> <img alt="image" width="1392" src="https://user-images.githubusercontent.com/46499312/225850675-19bff244-8ea9-4cc1-85c4-ca2b676cb4f4.png">

Can be marked done, if this is fixed!

**Comment by AlarWE** [comment]
@vmugra Prototype updated.

**Comment by vmugra** [comment]
Accepted!

**Comment by bartekpospiech** [comment]
@Kristjan259 I believe this need to be developed also, maybe we could groom this?

**Comment by turnerrainer** [comment]
Blocked due to Ruuter responding with `HTTP 300`

**Comment by ExiRain** [comment]
Added fixed on displaying the page(columns no longer display 'undefined' if no value is set for them) [PR](https://github.com/buerokratt/Training-Module/pull/371)

**Comment by Kristjan259** [comment]
When trying to add example to an intent, I get internal server error.
![Screenshot 2024-02-14 at 15 31 17](https://github.com/buerokratt/Training-Module/assets/5470201/4e03c58b-2d55-45f5-a7ae-a204d6fd5500)

**Comment by Kristjan259** [comment]
The responses that are given by the customer service agent are displayed badly. 

![Image](https://github.com/buerokratt/Training-Module/assets/5470201/cefbfc13-18f1-400c-a1f1-9ed16762be26)

**Comment by ExiRain** [comment]
Ok, i had it a bit different in local and didnt notice this part.
[Pull request](https://github.com/buerokratt/Training-Module/pull/381) with fix

**Comment by Kristjan259** [comment]
"Flag conversation and highlight it in the conversation list" - I dont know what is meant by this, but otherwise looks good.
