### ISSUE TITLE
Copy text in training module history chats

### ISSUE THREAD

**Issue by ffrose** [buerokratt/Training-Module#710]
**AS A** *Trainer*
**I WANT** *to copy text in Bürokratt training module, that has written in Chatbot*
**SO THAT** *I can easily paste it where needed*

### Acceptance Criteria

- [x] In Bürokratt Training module Trainer has the option to copy text that has been written in Chatbot.

![Image](https://github.com/user-attachments/assets/ff3dd776-a9c2-4a7f-8f82-56c815de9693)

**Additional**

Same logic has been implemented in Chat module https://github.com/buerokratt/Buerokratt-Chatbot/issues/1004

**Comment by ExiRain** [comment]
Should work now:

Related [PR](https://github.com/buerokratt/Training-Module/pull/713).

**Comment by ffrose** [comment]
Works as intended.
