### ISSUE TITLE
Add, update, and delete examples of a specified Rasa intent

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#79]
AS A Trainer
I WANT TO add, update and delete examples of a specific Rasa intent
SO THAT I could manipulate training data and models based on it

### Acceptance Criteria

> See [temporary list of related API endpoints](https://github.com/buerokratt/Buerokratt-onboarding/issues/8)

> List of intents - https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/tree/main/data/nlu

> Sample `YAML` file with intents and their examples - https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/data/nlu/common_teenus_ilm_nlu.yml

#### List examples of a specified intent

- [ ] Use POST service `/intents/examples` to list all examples of a specified intent
- [ ] Examples of a specified intent are fetched from an appropriate YAML file

#### Add new examples

- [x] POST service `/intents/examples/add` to add new examples
- [x] Multiple examples can be used as input
- [x] Duplicate examples can not be added
- [ ] Changes apply on an appropriate YAML file
- [ ] Limit example length as a hardcoded value in Ruuter DSL
- [ ] Intent release ban if the minimum amount of examples is not exceeded is set as a hardcoded value in Ruuter DSL

#### Update existing examples

- [x] POST service `/intents/examples/update` to update examples of an existing intent
- [ ] New value may not be a duplicate of an already existing one
- [ ] Changes apply on an appropriate YAML file

#### Delete existing examples

- [x] POST service `/intents/examples/delete` to delete a specified example of an existing intent
- [ ] Changes apply on an appropriate YAML file

**Comment by RaulAltmae** [comment]
list `/intents/examples` works with OpenSearch and it is described in this task https://github.com/buerokratt/Training-Module/issues/78

**Comment by RaulAltmae** [comment]
i added endpoint for fetching examples from files.
sample input for `/intents/examples/list` 
```json
{
    "intent": "common_teenus_ilm"
}
```

**Comment by RaulAltmae** [comment]
sample input for `/intents/examples/add`
```json
{
  "intent": "common_teenus_ilm",
  "examples": [
    "test",
    "test1"
  ]
}
```

**Comment by RaulAltmae** [comment]
sample input for `/intents/examples/update`
```json
{
  "intent": "common_teenus_ilm",
  "example": "ilm",
  "new_example": "ilm täna"
}
```

**Comment by RaulAltmae** [comment]
sample input for `/intents/examples/delete`
```json
{
  "intent": "common_teenus_ilm",
  "example": "ilm"
}
```

**Comment by turnerrainer** [comment]
@RaulAltmae please link this issue with an appropriate pull request.

**Comment by RaulAltmae** [comment]
Pull requests https://github.com/buerokratt/Training-Module/pull/173 https://github.com/buerokratt/Training-Module/pull/174 https://github.com/buerokratt/Training-Module/pull/175 https://github.com/buerokratt/Training-Module/pull/178

**Comment by KasparMinn** [comment]
PR: https://github.com/buerokratt/Training-Module/pull/283

This pull request finalizes the add, update, and delete functionalities in examples.

The front-end is now slightly reworked with data being fetched for both intents and examples at once to avoid making too many requests and for the inevitable necessity of having to fetch entire intents for updating and saving examples anyway. LoadingDialogue is added to making change operations with examples and there is some refactor of things happening on the screen and in the background due to create, update, and delete requests all taking a bit of time to fetch back data. 

- Refactored front-end to properly process all requests.
- Added OpenSearch and Database calls to update state together with file system updates.
- Solved a variety of bugs in back-end (pipe symbol, nesting problems, empty intent issues).

**Comment by Kristjan259** [comment]
Changes (adding, updateing and deleteing) are only seen after a page refresh.

**Comment by turnerrainer** [comment]
Same bug as #74

**Comment by ValterAro** [comment]
[BUG]
Short summary: When adding examples to an intent you can edit an existing example to be the same as another example.
Expected result: You should not be able to enter the same example as another examle.
Real result: Even though when editing the example and adding the exact same words then the example is added and there is no error.
How to reproduce: login, go to https://admin.dev.buerokratt.ee/training/training/intents and select an intent where to add example. Then add two different examples and then modify one to be exactly like the other.
Pic:


![Image](https://github.com/buerokratt/Training-Module/assets/122787093/a210f0be-41a3-4653-91cf-e85da8f3dc43)

**Comment by KasparMinn** [comment]
PR to fix disallow creating duplicate examples by updating: https://github.com/buerokratt/Training-Module/pull/375
